@serverHost = http://localhost:8080
@V1_API = v1/api 
@DEPTH1 = TO
@DEPTH2 = 02
@SCREEN_ID = TO02A006
@TRX_REQUEST = trxRequest
# Today Asset
### TO02A006/MAAM3017 Post
POST {{serverHost}}/{{V1_API}}/trxRequest/{{DEPTH1}}/{{DEPTH2}}/{{SCREEN_ID}}
Content-Type: application/json

[
    {
        "trId"  : "MAQM1011",     
        "input" : {
            "input1": "C000000002",
            "inqClsfNm": "01"
        }
    },
    {
        "trId"  : "MAAM3017",     
        "input" : {
            "input1": "C000000002",
            "input2": "",
            "inqClsfNm": "01",
            "nxtKeyC": ""
        }
    }
]

### TO02A006/MAAM3017 Post
POST {{serverHost}}/{{V1_API}}/trxRequest/{{DEPTH1}}/{{DEPTH2}}/{{SCREEN_ID}}
Content-Type: application/json

[
    {
        "trId"  : "MAAM3018",
        "input" : {
            "input1": "C000000001",
            "input3": "",
            "Record1": [
                {
                    "input1": "C000000001",
                    "input2": "현금기타",
                    "input3": "현금기타",
                    "input4": "300000"
                },
                {
                    "input1": "C000000001",
                    "input2": "기타",
                    "input3": "기타",
                    "input4": "100000"
                }
            ],
            "input1": "INSERT TEST",
            "input2": "77777",
            "input3": "777",
            "thingAddrC": "서울시 테스트",
            "useArP2": "777.00",
            "input6": "77",
            "input7": "777777",

            "lndngF": "7",
            "lsGamt": "7777",
            "mmRntAmt": "777",
            "astsDstgChrsNo": "77xp 7777",
            "yr": "2021",
            "carOptInfoC": "차량옵션",
            "carInfoC": "차량정보"            
        }
    } 
]


### TO02A002/MAQM3013
# 홈 > 총자산 > 자산유형별 증감 목록 조회
# - 
POST {{serverHost}}/{{V1_API}}/trxRequest/{{DEPTH1}}/{{DEPTH2}}/TO02A002
Content-Type: application/json

[
    {
        "trId"  : "MAQM3013",
        "input" : {
            "input1": "C000000001"
        }
    } 
]


### TO02A002/MAQM3014
# 홈 > 총자산 > 자산유형별 증감 상세 조회
# - input2의 유형코드에따른 상세정보를 조회한다 (01:현금 / 02:투자 / 03:카드 / 04:보험 / 05:연금 / 06:실물 / 07:대출)
POST {{serverHost}}/{{V1_API}}/trxRequest/{{DEPTH1}}/{{DEPTH2}}/TO02A002
Content-Type: application/json

[
    {
        "trId"  : "MAQM3014",
        "input" : {
            "input1": "C000000001",
            "input2": "02",
            "nxtKey": ""
        }
    } 
]


### TO02A002/MAQM3015 - 단위테스트결과서 없음
# 홈 > 총자산 > 금융사별 증감 목록 조회
POST {{serverHost}}/{{V1_API}}/{{TRX_REQUEST}}/{{DEPTH1}}/{{DEPTH2}}/TO02A002
Content-Type: application/json

[
    {
        "trId"  : "MAQM3015",
        "input" : {
            "input1": "C000000001"
        }
    } 
]


### TO02A002/MAQM3016 - 단위테스트결과서 없음
# 홈 > 총자산 > 금융사별 증감 상세 조회
POST {{serverHost}}/{{V1_API}}/{{TRX_REQUEST}}/{{DEPTH1}}/{{DEPTH2}}/TO02A002
Content-Type: application/json

[
    {
        "trId"  : "MAQM3016",
        "input" : {
            "input1": "C000000001"
        }
    }
]